services:

  frontend:
    image: faizanite/mern-taskmanager-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: faizanite/mern-taskmanager-backend:latest
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: mongodb://mongo:27017/taskmanager
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: